from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

def connect_db(app):
    db.init_app(app)

class Trainer(db.Model):
    __tablename__ = 'trainer'
    __table_args__ = {'extend_existing': True} 
    id = db.Column(db.String, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    email = db.Column(db.String(64),unique=True)
    clients = db.relationship('Client', backref='trainer', lazy=True, cascade="all, delete-orphan")

class Client(db.Model):
    __tablename__ = 'client'
    __table_args__ = {'extend_existing': True} 
    id = db.Column(db.String, primary_key=True)
    trainer_id = db.Column(db.String, db.ForeignKey('trainer.id'))
    name = db.Column(db.String(64))
    email = db.Column(db.String(64))
    meal_plan_id = db.Column(db.Integer, db.ForeignKey('meal_plan.id'))
    meal_plan = db.relationship("MealPlan", back_populates="client")
    workouts = db.relationship('Workout', backref='client', lazy=True, cascade="all, delete-orphan")

class Workout(db.Model):
    __tablename__ = 'workout'
    __table_args__ = {'extend_existing': True} 
    id = db.Column(db.String, primary_key=True)
    client_id = db.Column(db.String, db.ForeignKey('client.id'))
    name = db.Column(db.String(64))
    description = db.Column(db.String(128))

class MealPlan(db.Model):
    __tablename__ = 'meal_plan'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)
    client = db.relationship("Client", back_populates="meal_plan")
    monday_breakfast = db.Column(db.String)
    monday_breakfast_calories = db.Column(db.Integer)
    monday_breakfast_protein = db.Column(db.Integer)
    monday_breakfast_carbs = db.Column(db.Integer)
    monday_breakfast_fat = db.Column(db.Integer)
    monday_snack1 = db.Column(db.String)
    monday_snack1_calories = db.Column(db.Integer)
    monday_snack1_protein = db.Column(db.Integer)
    monday_snack1_carbs = db.Column(db.Integer)
    monday_snack1_fat = db.Column(db.Integer)
    monday_lunch = db.Column(db.String)
    monday_lunch_calories = db.Column(db.Integer)
    monday_lunch_protein = db.Column(db.Integer)
    monday_lunch_carbs = db.Column(db.Integer)
    monday_lunch_fat = db.Column(db.Integer)
    monday_snack2 = db.Column(db.String)
    monday_snack2_calories = db.Column(db.Integer)
    monday_snack2_protein = db.Column(db.Integer)
    monday_snack2_carbs = db.Column(db.Integer)
    monday_snack2_fat = db.Column(db.Integer)
    monday_dinner = db.Column(db.String)
    monday_dinner_calories = db.Column(db.Integer)
    monday_dinner_protein = db.Column(db.Integer)
    monday_dinner_carbs = db.Column(db.Integer)
    monday_dinner_fat = db.Column(db.Integer)
    tuesday_breakfast = db.Column(db.String)
    tuesday_breakfast_calories = db.Column(db.Integer)
    tuesday_breakfast_protein = db.Column(db.Integer)
    tuesday_breakfast_carbs = db.Column(db.Integer)
    tuesday_breakfast_fat = db.Column(db.Integer)
    tuesday_snack1 = db.Column(db.String)
    tuesday_snack1_calories = db.Column(db.Integer)
    tuesday_snack1_protein = db.Column(db.Integer)
    tuesday_snack1_carbs = db.Column(db.Integer)
    tuesday_snack1_fat = db.Column(db.Integer)
    tuesday_lunch = db.Column(db.String)
    tuesday_lunch_calories = db.Column(db.Integer)
    tuesday_lunch_protein = db.Column(db.Integer)
    tuesday_lunch_carbs = db.Column(db.Integer)
    tuesday_lunch_fat = db.Column(db.Integer)
    tuesday_snack2 = db.Column(db.String)
    tuesday_snack2_calories = db.Column(db.Integer)
    tuesday_snack2_protein = db.Column(db.Integer)
    tuesday_snack2_carbs = db.Column(db.Integer)
    tuesday_snack2_fat = db.Column(db.Integer)
    tuesday_dinner = db.Column(db.String)
    tuesday_dinner_calories = db.Column(db.Integer)
    tuesday_dinner_protein = db.Column(db.Integer)
    tuesday_dinner_carbs = db.Column(db.Integer)
    tuesday_dinner_fat = db.Column(db.Integer)
    wednesday_breakfast = db.Column(db.String)
    wednesday_breakfast_calories = db.Column(db.Integer)
    wednesday_breakfast_protein = db.Column(db.Integer)
    wednesday_breakfast_carbs = db.Column(db.Integer)
    wednesday_breakfast_fat = db.Column(db.Integer)
    wednesday_snack1 = db.Column(db.String)
    wednesday_snack1_calories = db.Column(db.Integer)
    wednesday_snack1_protein = db.Column(db.Integer)
    wednesday_snack1_carbs = db.Column(db.Integer)
    wednesday_snack1_fat = db.Column(db.Integer)
    wednesday_lunch = db.Column(db.String)
    wednesday_lunch_calories = db.Column(db.Integer)
    wednesday_lunch_protein = db.Column(db.Integer)
    wednesday_lunch_carbs = db.Column(db.Integer)
    wednesday_lunch_fat = db.Column(db.Integer)
    wednesday_snack2 = db.Column(db.String)
    wednesday_snack2_calories = db.Column(db.Integer)
    wednesday_snack2_protein = db.Column(db.Integer)
    wednesday_snack2_carbs = db.Column(db.Integer)
    wednesday_snack2_fat = db.Column(db.Integer)
    wednesday_dinner = db.Column(db.String)
    wednesday_dinner_calories = db.Column(db.Integer)
    wednesday_dinner_protein = db.Column(db.Integer)
    wednesday_dinner_carbs = db.Column(db.Integer)
    wednesday_dinner_fat = db.Column(db.Integer)
    thursday_breakfast = db.Column(db.String)
    thursday_breakfast_calories = db.Column(db.Integer)
    thursday_breakfast_protein = db.Column(db.Integer)
    thursday_breakfast_carbs = db.Column(db.Integer)
    thursday_breakfast_fat = db.Column(db.Integer)
    thursday_snack1 = db.Column(db.String)
    thursday_snack1_calories = db.Column(db.Integer)
    thursday_snack1_protein = db.Column(db.Integer)
    thursday_snack1_carbs = db.Column(db.Integer)
    thursday_snack1_fat = db.Column(db.Integer)
    thursday_lunch = db.Column(db.String)
    thursday_lunch_calories = db.Column(db.Integer)
    thursday_lunch_protein = db.Column(db.Integer)
    thursday_lunch_carbs = db.Column(db.Integer)
    thursday_lunch_fat = db.Column(db.Integer)
    thursday_snack2 = db.Column(db.String)
    thursday_snack2_calories = db.Column(db.Integer)
    thursday_snack2_protein = db.Column(db.Integer)
    thursday_snack2_carbs = db.Column(db.Integer)
    thursday_snack2_fat = db.Column(db.Integer)
    thursday_dinner = db.Column(db.String)
    thursday_dinner_calories = db.Column(db.Integer)
    thursday_dinner_protein = db.Column(db.Integer)
    thursday_dinner_carbs = db.Column(db.Integer)
    thursday_dinner_fat = db.Column(db.Integer)
    friday_breakfast = db.Column(db.String)
    friday_breakfast_calories = db.Column(db.Integer)
    friday_breakfast_protein = db.Column(db.Integer)
    friday_breakfast_carbs = db.Column(db.Integer)
    friday_breakfast_fat = db.Column(db.Integer)
    friday_snack1 = db.Column(db.String)
    friday_snack1_calories = db.Column(db.Integer)
    friday_snack1_protein = db.Column(db.Integer)
    friday_snack1_carbs = db.Column(db.Integer)
    friday_snack1_fat = db.Column(db.Integer)
    friday_lunch = db.Column(db.String)
    friday_lunch_calories = db.Column(db.Integer)
    friday_lunch_protein = db.Column(db.Integer)
    friday_lunch_carbs = db.Column(db.Integer)
    friday_lunch_fat = db.Column(db.Integer)
    friday_snack2 = db.Column(db.String)
    friday_snack2_calories = db.Column(db.Integer)
    friday_snack2_protein = db.Column(db.Integer)
    friday_snack2_carbs = db.Column(db.Integer)
    friday_snack2_fat = db.Column(db.Integer)
    friday_dinner = db.Column(db.String)
    friday_dinner_calories = db.Column(db.Integer)
    friday_dinner_protein = db.Column(db.Integer)
    friday_dinner_carbs = db.Column(db.Integer)
    friday_dinner_fat = db.Column(db.Integer)
    saturday_breakfast = db.Column(db.String)
    saturday_breakfast_calories = db.Column(db.Integer)
    saturday_breakfast_protein = db.Column(db.Integer)
    saturday_breakfast_carbs = db.Column(db.Integer)
    saturday_breakfast_fat = db.Column(db.Integer)
    saturday_snack1 = db.Column(db.String)
    saturday_snack1_calories = db.Column(db.Integer)
    saturday_snack1_protein = db.Column(db.Integer)
    saturday_snack1_carbs = db.Column(db.Integer)
    saturday_snack1_fat = db.Column(db.Integer)
    saturday_lunch = db.Column(db.String)
    saturday_lunch_calories = db.Column(db.Integer)
    saturday_lunch_protein = db.Column(db.Integer)
    saturday_lunch_carbs = db.Column(db.Integer)
    saturday_lunch_fat = db.Column(db.Integer)
    saturday_snack2 = db.Column(db.String)
    saturday_snack2_calories = db.Column(db.Integer)
    saturday_snack2_protein = db.Column(db.Integer)
    saturday_snack2_carbs = db.Column(db.Integer)
    saturday_snack2_fat = db.Column(db.Integer)
    saturday_dinner = db.Column(db.String)
    saturday_dinner_calories = db.Column(db.Integer)
    saturday_dinner_protein = db.Column(db.Integer)
    saturday_dinner_carbs = db.Column(db.Integer)
    saturday_dinner_fat = db.Column(db.Integer)
    sunday_breakfast = db.Column(db.String)
    sunday_breakfast_calories = db.Column(db.Integer)
    sunday_breakfast_protein = db.Column(db.Integer)
    sunday_breakfast_carbs = db.Column(db.Integer)
    sunday_breakfast_fat = db.Column(db.Integer)
    sunday_snack1 = db.Column(db.String)
    sunday_snack1_calories = db.Column(db.Integer)
    sunday_snack1_protein = db.Column(db.Integer)
    sunday_snack1_carbs = db.Column(db.Integer)
    sunday_snack1_fat = db.Column(db.Integer)
    sunday_lunch = db.Column(db.String)
    sunday_lunch_calories = db.Column(db.Integer)
    sunday_lunch_protein = db.Column(db.Integer)
    sunday_lunch_carbs = db.Column(db.Integer)
    sunday_lunch_fat = db.Column(db.Integer)
    sunday_snack2 = db.Column(db.String)
    sunday_snack2_calories = db.Column(db.Integer)
    sunday_snack2_protein = db.Column(db.Integer)
    sunday_snack2_carbs = db.Column(db.Integer)
    sunday_snack2_fat = db.Column(db.Integer)
    sunday_dinner = db.Column(db.String)
    sunday_dinner_calories = db.Column(db.Integer)
    sunday_dinner_protein = db.Column(db.Integer)
    sunday_dinner_carbs = db.Column(db.Integer)
    sunday_dinner_fat = db.Column(db.Integer)
    

